---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 04.08.18 18:14
---

local RPD = require "scripts/lib/commonClasses"

local actor = require "scripts/lib/actor"

local dungeonEntrance = { 13, 4 }
local shopEntrance = { 18, 16 }

local lastWarningTime = 0
local time = 0

return actor.init({
    act = function()
        local hero = RPD.Dungeon.hero

        if hero:getBelongings():getItem("TomeOfMastery") ~= nil then
            hero:getBelongings():getItem("TomeOfMastery"):detach(hero:getBelongings().backpack)
        end

        return true
    end,


    actionTime = function()
        return 1
    end,


    activate = function()
    end
})